CREATE DATABASE IF NOT EXISTS registro_ventas;

USE registro_ventas;

CREATE TABLE IF NOT EXISTS USUARIOS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(64) NOT NULL,
	apellido VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	estado BOOLEAN NOT NULL,
	id_rol INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ROLES (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(255) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	estado BOOLEAN NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS MODULOS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(64) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS MODULOS_ROL (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	id_rol INTEGER NOT NULL,
	id_modulo INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BANCOS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(64) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS FORMAR_PAGO (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(64) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	estado BOOLEAN NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TIPOS_VENTAS_ABONOS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(64) NOT NULL,
	fecha_creacion BOOLEAN NOT NULL,
	estado BOOLEAN NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ALMACENES (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	nombre VARCHAR(64) NOT NULL,
	direccion VARCHAR(128) NOT NULL,
	telefono VARCHAR(16) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	estado BOOLEAN NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS CUENTAS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	numero VARCHAR(32) NOT NULL,
	titular VARCHAR(64) NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	estado BOOLEAN NOT NULL,
	id_banco INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TRANSACCIONES_VENTAS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	id_cliente INTEGER,
	valor FLOAT,
	id_forma_pago INTEGER NOT NULL,
	fecha_consignacion DATE,
	fecha_cheque DATE,
	num_cheque INTEGER,
	num_aprobacion INTEGER,
	id_tipo_venta INTEGER NOT NULL,
	id_banco INTEGER,
	id_cuenta INTEGER NOT NULL,
	id_venta INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PLANILLAS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	num_consecutivo INTEGER NOT NULL,
	fecha_creacion DATETIME NOT NULL,
	id_almacen INTEGER NOT NULL,
	observaciones VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ABONOS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	cliente VARCHAR(64) NOT NULL,
	num_recibo INTEGER NOT NULL,
	valor FLOAT NOT NULL,
	id_forma_pago INTEGER NOT NULL,
	descripcion_forma_pago VARCHAR(255) NOT NULL,
	fecha_consignacion DATE,
	num_cheque INTEGER,
	fecha_cheque DATE,
	id_banco INTEGER,
	id_tipo_abono INTEGER NOT NULL,
	id_venta INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS GASTOS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	detalle VARCHAR(255) NOT NULL,
	num_recibo INTEGER NOT NULL,
	valor FLOAT NOT NULL,
	id_planilla INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS NOTAS_CREDITO (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	cliente VARCHAR(64) NOT NULL,
	referencia VARCHAR(64) NOT NULL,
	metraje INTEGER NOT NULL,
	valor_unitario FLOAT NOT NULL,
	valor_total FLOAT NOT NULL,
	id_venta INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS CLIENTES (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	identificacion VARCHAR(32) NOT NULL,
	nombres VARCHAR(255) NOT NULL,
	apellidos VARCHAR(255) NOT NULL,
	telefono VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS VENTAS (
	id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
	num_factura INTEGER NOT NULL,
	valor_venta INTEGER NOT NULL,
	id_planilla INTEGER NOT NULL,
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_fk6 FOREIGN KEY (id_rol) REFERENCES ROLES(id);

ALTER TABLE MODULOS_ROL ADD CONSTRAINT MODULOS_ROL_fk1 FOREIGN KEY (id_rol) REFERENCES ROLES(id);

ALTER TABLE MODULOS_ROL ADD CONSTRAINT MODULOS_ROL_fk2 FOREIGN KEY (id_modulo) REFERENCES MODULOS(id);

ALTER TABLE CUENTAS ADD CONSTRAINT CUENTAS_fk5 FOREIGN KEY (id_banco) REFERENCES BANCOS(id);

ALTER TABLE TRANSACCIONES_VENTAS ADD CONSTRAINT TRANSACCIONES_VENTAS_fk1 FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id);

ALTER TABLE TRANSACCIONES_VENTAS ADD CONSTRAINT TRANSACCIONES_VENTAS_fk3 FOREIGN KEY (id_forma_pago) REFERENCES FORMAR_PAGO(id);

ALTER TABLE TRANSACCIONES_VENTAS ADD CONSTRAINT TRANSACCIONES_VENTAS_fk8 FOREIGN KEY (id_tipo_venta) REFERENCES TIPOS_VENTAS_ABONOS(id);

ALTER TABLE TRANSACCIONES_VENTAS ADD CONSTRAINT TRANSACCIONES_VENTAS_fk9 FOREIGN KEY (id_banco) REFERENCES BANCOS(id);

ALTER TABLE TRANSACCIONES_VENTAS ADD CONSTRAINT TRANSACCIONES_VENTAS_fk10 FOREIGN KEY (id_cuenta) REFERENCES CUENTAS(id);

ALTER TABLE TRANSACCIONES_VENTAS ADD CONSTRAINT TRANSACCIONES_VENTAS_fk11 FOREIGN KEY (id_venta) REFERENCES VENTAS(id);

ALTER TABLE PLANILLAS ADD CONSTRAINT PLANILLAS_fk3 FOREIGN KEY (id_almacen) REFERENCES ALMACENES(id);

ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_fk4 FOREIGN KEY (id_forma_pago) REFERENCES FORMAR_PAGO(id);

ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_fk9 FOREIGN KEY (id_banco) REFERENCES BANCOS(id);

ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_fk10 FOREIGN KEY (id_tipo_abono) REFERENCES TIPOS_VENTAS_ABONOS(id);

ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_fk11 FOREIGN KEY (id_venta) REFERENCES VENTAS(id);

ALTER TABLE GASTOS ADD CONSTRAINT GASTOS_fk4 FOREIGN KEY (id_planilla) REFERENCES PLANILLAS(id);

ALTER TABLE NOTAS_CREDITO ADD CONSTRAINT NOTAS_CREDITO_fk6 FOREIGN KEY (id_venta) REFERENCES TRANSACCIONES_VENTAS(id);

ALTER TABLE VENTAS ADD CONSTRAINT VENTAS_fk3 FOREIGN KEY (id_planilla) REFERENCES PLANILLAS(id);

COMMIT;